# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configManager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfigManager.proto\x12\rConfigManager\"\t\n\x07NoParam\"\"\n\x06Socket\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"\x80\x01\n\x17ModbusTCPConfigResponse\x12\x34\n\x15modbusTCPServerConfig\x18\x01 \x01(\x0b\x32\x15.ConfigManager.Socket\x12/\n\x10mqttServerConfig\x18\x02 \x01(\x0b\x32\x15.ConfigManager.Socket\"r\n\x12MQTTConfigResponse\x12/\n\x10mqttServerConfig\x18\x01 \x01(\x0b\x32\x15.ConfigManager.Socket\x12+\n\x0c\x62rokerConfig\x18\x02 \x01(\x0b\x32\x15.ConfigManager.Socket2\xb1\x01\n\rConfigManager\x12J\n\rgetMQTTConfig\x12\x16.ConfigManager.NoParam\x1a!.ConfigManager.MQTTConfigResponse\x12T\n\x12getModbusTCPConfig\x12\x16.ConfigManager.NoParam\x1a&.ConfigManager.ModbusTCPConfigResponseb\x06proto3')



_NOPARAM = DESCRIPTOR.message_types_by_name['NoParam']
_SOCKET = DESCRIPTOR.message_types_by_name['Socket']
_MODBUSTCPCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['ModbusTCPConfigResponse']
_MQTTCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['MQTTConfigResponse']
NoParam = _reflection.GeneratedProtocolMessageType('NoParam', (_message.Message,), {
  'DESCRIPTOR' : _NOPARAM,
  '__module__' : 'configManager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigManager.NoParam)
  })
_sym_db.RegisterMessage(NoParam)

Socket = _reflection.GeneratedProtocolMessageType('Socket', (_message.Message,), {
  'DESCRIPTOR' : _SOCKET,
  '__module__' : 'configManager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigManager.Socket)
  })
_sym_db.RegisterMessage(Socket)

ModbusTCPConfigResponse = _reflection.GeneratedProtocolMessageType('ModbusTCPConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODBUSTCPCONFIGRESPONSE,
  '__module__' : 'configManager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigManager.ModbusTCPConfigResponse)
  })
_sym_db.RegisterMessage(ModbusTCPConfigResponse)

MQTTConfigResponse = _reflection.GeneratedProtocolMessageType('MQTTConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _MQTTCONFIGRESPONSE,
  '__module__' : 'configManager_pb2'
  # @@protoc_insertion_point(class_scope:ConfigManager.MQTTConfigResponse)
  })
_sym_db.RegisterMessage(MQTTConfigResponse)

_CONFIGMANAGER = DESCRIPTOR.services_by_name['ConfigManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOPARAM._serialized_start=38
  _NOPARAM._serialized_end=47
  _SOCKET._serialized_start=49
  _SOCKET._serialized_end=83
  _MODBUSTCPCONFIGRESPONSE._serialized_start=86
  _MODBUSTCPCONFIGRESPONSE._serialized_end=214
  _MQTTCONFIGRESPONSE._serialized_start=216
  _MQTTCONFIGRESPONSE._serialized_end=330
  _CONFIGMANAGER._serialized_start=333
  _CONFIGMANAGER._serialized_end=510
# @@protoc_insertion_point(module_scope)
